/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triviagame;

// import java.net.URI;
// import java.net.URISyntaxException;

// import io.socket.client.IO;
// import io.socket.client.Socket;
// import io.socket.emitter.Emitter;
// import javafx.scene.Scene;
// import javafx.fxml.FXMLLoader;
// import javafx.scene.Parent;

//exceptions
import java.io.IOException;

//javafx
import javafx.application.Application;
import javafx.stage.Stage;

//terminate application
import javafx.application.Platform;
// import javafx.event.EventHandler;
// import javafx.stage.WindowEvent;

//Handlers
import triviagame.handlers.SocketHandler;
import triviagame.handlers.StageHandler;

public class App extends Application {

    // Stage sceneHandler;
    SocketHandler socketHandler;
    StageHandler stageHandler;

    //pagina loading
    @Override
    public void start(Stage stage) throws IOException {
        //iniciar javafx
        stageHandler = Globals.stageHandler;
        socketHandler = Globals.socketHandler;
        stageHandler.init(stage);
        socketHandler.init();

        // //deletar todas as threads e sockets
        // stage.setOnCloseRequest(new EventHandler<WindowEvent>() {
        //     @Override
        //     public void handle(WindowEvent e) {
        //         socketHandler.terminate();
        //         Platform.exit();
        //         System.exit(0);
        //     }
        // });
    }

    public static void main(String[] args) {
        launch();
        
        //deletar todas as threads e sockets
        Globals.socketHandler.terminate();
        Platform.exit();
        System.exit(0);

    }
}