/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triviagame.handlers;

import java.io.IOException;

// import java.net.URI;
// import java.net.URISyntaxException;

// import io.socket.client.IO;
// import io.socket.client.Socket;
// import io.socket.emitter.Emitter;
// import javafx.application.Application;

import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;

public class StageHandler{

    private Stage stage;
    private Object fxmlController;

    //macaroni
    Boolean sceneFinish = false;

    // pagina loading
    public void init(Stage stage) throws IOException {
        this.stage = stage;
        //iniciar javafx
        stage.setTitle("Trivia Game");
        changeScene("/pages/pageLoading.fxml");
    }

    // public StageHandler(Stage stage){
    //     this.stage = stage;
    // }

    public void changeScene(String resource) throws IOException {
        Platform.runLater(() -> {
            // Update UI here.        
            try{
                FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource(resource));
                Parent root = fxmlLoader.load();
                Scene tela = new Scene(root);
                stage.setScene(tela);
                stage.show();
                fxmlController = fxmlLoader.getController();
                // System.out.println("controller "+ fxmlController.getClass());
                
            } catch(Exception e){
                System.out.println("Exception Error: " + e);
            }
        });
    }

    // public synchronized void changeSceneSynchronous(String resource) throws IOException {
    public void changeSceneSynchronous(String resource) throws IOException {
        setFinish(false);

        Platform.runLater(() -> {
            // Update UI here.        
            try{
                FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource(resource));
                Parent root = fxmlLoader.load();
                Scene tela = new Scene(root);
                stage.setScene(tela);
                stage.show();
                fxmlController = fxmlLoader.getController();
                // System.out.println("controller "+ fxmlController.getClass());

                setFinish(true);
                
            } catch(Exception e){
                System.out.println("Exception Error: " + e);
            }
        });

        while(getFinish() != true) {
            try{
                Thread.sleep(1);
            } catch(Exception e){
                System.out.println("Exception Error: " + e);
            }
        }
    }

    private void setFinish(Boolean value){
        sceneFinish = value;
    }

    private Boolean getFinish(){
        return sceneFinish;
    }

    public Object getSceneController(){
        return fxmlController;
    }

        // new Socket

        // //conectar ao servidor
        // try {
        //     //crio socket
        //     URI uri = URI.create("http://localhost:5000");
        //     IO.Options options = IO.Options.builder().build();
        //     socket = IO.socket(uri, options);

        //     //conecto no socket
        //     socket.connect();

        //     //recebo mensagens
        //     socket.once("connectReply", new Emitter.Listener() {
        //         @Override
        //         public void call(Object... args) {
        //             System.out.println("Conectado.");
        //         }
        //     });

        // } catch(Exception ex) {
        //     if(socket != null){
        //         socket.disconnect();
        //         System.out.println("Disconectado. " + socket);
        //     }
        //     System.out.println("Exception Error: " + ex);

        // } finally {
        //     // if(socket != null){
        //     //     socket.disconnect();
        //     //     System.out.println("Disconectado. " + socket);
        //     // }
        // }
    // }

    // public static void main(String[] args) {
    //     App app = new App();
        
    //     launch();
    //     // //crio socket
    //     // URI uri = URI.create("http://localhost:5000");
    //     // IO.Options options = IO.Options.builder().build();
    //     // Socket socket = IO.socket(uri, options);

    //     // //conecto no socket
    //     // socket.connect();
    //     System.out.println("fechando.");

    //     // //emito mensagens
    //     // socket.emit("my_message", "testando 123");
    //     // socket.emit("hello", "world");

    //     // //recebo mensagens
    //     // socket.on("world", new Emitter.Listener() {
    //     //     @Override
    //     //     public void call(Object... args) {
    //     //         System.out.println("hello world!!!!!. -> " + args[0]);
    //     //     }
    //     // });


    //     //abrir pagina de conectar
    // }
}